### PR TITLE
Fix cleanup

### LINKED ISSUE #27: Remove testthat:: and identify/update other formatting issues to be closer inline with admiral

### LINKED ISSUE #34: Bring over Nathan's or Admiral spell check lists

### LINKED ISSUE #41: timberAddin() styles.css error
styles.css gets moved up a level, out of inst/ when installed, so the addin throws an error.

image

```
> timber:::timberAddin()
Warning in file(con, "r") :
  cannot open file 'inst/styles.css': No such file or directory
Error in file(con, "r") : cannot open the connection
```

### PR DESCRIPTION
**Pull request by kodesiba**
- update writer for session_info
- remove logs from testthat/ref
- add inst/WORDLIST to enable use of {spelling}, closes #34 
- update documentation to fix spelling errors found
- remove explicit `testthat::` calls in unit tests files, closes #27 
- update timberAddIn to have explicit css in taglist closes #41

### CODE REVIEW

File: R/writer.R [hunk 1]
```diff
@@ -51,8 +51,8 @@ write_session_info <- function(){
       map_chr(~ ifelse(nchar(.x) > 80 & grepl("\u2500\u2500\u2500\u2500", .x),
                    substring(.x, 1, 80),
                    .x)) %>%
-      # wrap any other elements over 78 characters
-      map_chr(~ stri_wrap(.x, width = 78, exdent = 2, simplify = FALSE,
+      # wrap any other elements over 80 characters
+      map_chr(~ stri_wrap(.x, width = 80, exdent = 2, simplify = FALSE,
```
Comment (nicholas-masel) [inline R/writer.R:55]: I tried this out and see the line after session ino wraps.  Is this expected?


─ Session info
	  ─────────────────────────────────────────────────────────────────

Comment (nicholas-masel) [inline R/writer.R:55]: I tried this out and see the line after session ino wraps.  Is this expected?


─ Session info
	  ─────────────────────────────────────────────────────────────────

Comment (nicholas-masel) [inline R/writer.R:55]: add `use_length = TRUE`

Comment (nicholas-masel) [inline R/writer.R:55]: add `use_length = TRUE`

Comment (nicholas-masel) [inline R/writer.R:55]:
```suggestion
      map_chr(~ stri_wrap(.x, width = 80, exdent = 2, simplify = FALSE, use_length = TRUE,
```

Comment (nicholas-masel) [inline R/writer.R:55]:
```suggestion
      map_chr(~ stri_wrap(.x, width = 80, exdent = 2, simplify = FALSE, use_length = TRUE,
```

Comment (nicholas-masel) [reply R/writer.R:55]: See below, added `use_length = TRUE` and it looks ok for me now.

─ Session info ─────────────────────────────────────────────────────────────────
